# Generated by Django 3.0.12 on 2021-02-22 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('password', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('buy_date', models.DateField(verbose_name='Fecha de compra')),
                ('renoval_date', models.DateField(verbose_name='Fecha de renovación')),
                ('screen_number', models.IntegerField(default=0, verbose_name='Número de pantallas Totales')),
                ('available_screen_number', models.IntegerField(default=0, verbose_name='Número de pantallas disponibles')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('price', models.IntegerField(verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Platforma',
                'verbose_name_plural': 'Platformas',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField(verbose_name='Fecha de compra')),
                ('renoval_date', models.DateField(verbose_name='Fecha de renovación')),
                ('pin', models.CharField(max_length=4, verbose_name='PIN')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.Account', verbose_name='Cuenta')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pantalla',
                'verbose_name_plural': 'Pantallas',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.Platform', verbose_name='Plataforma'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
