# Generated by Django 3.0.12 on 2021-02-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='PIN'),
        ),
    ]
